//DELETE http://localhost:3001/stories/4

//POST http://localhost:3001/stories
//Content-Type: application/json

//{
//  "title": "Ocean Depths",
//  "description": "A mysterious adventure beneath the waves.",
//  "creator_id": null
//}


###Get all stories
GET http://localhost:3001/stories

###Get one story
GET http://localhost:3001/stories/1

###Get a story that does not exist
GET http://localhost:3001/stories/1111

//GET http://localhost:3001/stories/1/passages

//POST http://localhost:3001/stories/1/passages
//Content-Type: application/json

//{
 // "content": "You step into a clearing filled with glowing flowers.",
 // "is_ending": false
//}

//DELETE http://localhost:3001/stories/passages/5

//PATCH http://localhost:3001/stories/2
//Content-Type: application/json

//{
//  "title": "Ocean Depths — The Hidden Currents",
//  "description": "Beneath the waves lies a world of shifting currents, glowing creatures, and ancient secrets waiting to be uncovered.",
//  "creator_id": 5
//}

//PATCH http://localhost:3001/stories/passages/2
//Content-Type: application/json

//{
//  "content": "You follow the left path and discover a hidden waterfall.",
//  "is_ending": false
//}

//POST http://localhost:3001/passages/1/choices
//Content-Type: application/json

//{
 // "choice_text": "Follow the glowing lights",
 // "next_passage_id": 3
//}

//GET http://localhost:3001/passages/1/choices


//Get all users
//GET http://localhost:3001/users

//Get user by ID
//GET http://localhost:3001/users/1

//Create a user

//POST http://localhost:3001/users
//Content-Type: application/json

//{
// "name": "Marisol Vega",
//  "email": "marisol.vega@example.com",
//  "password_hash": "hashed_pw_3"
//}

//Update user
//PATCH http://localhost:3001/users/3
//Content-Type: application/json

//{
//  "name": "Ethan R.",
//  "email": "ethan.r@example.com",
//  "password_hash": "hashed_pw_3_updated"
//}

//Delete user
//DELETE http://localhost:3001/users/3
