//DELETE http://localhost:3001/stories/4

//POST http://localhost:3001/stories
//Content-Type: application/json

//{
//  "title": "Ocean Depths",
//  "description": "A mysterious adventure beneath the waves.",
//  "creator_id": null
//}

//GET http://localhost:3001/stories/1/passages

POST http://localhost:3001/stories/1/passages
Content-Type: application/json

{
  "content": "You step into a clearing filled with glowing flowers.",
  "is_ending": false
}